baseURL: https://mcamou.github.io/
languageCode: en-us
title: Welcome to the Ï€ dimension
theme:
  - hugo-atom-feed
  - paper

enableEmoji: true
enableGitInfo: true
disqusShortname: mcamou

permalinks:
  content: /:year/:month/:day/:title/

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - ATOM
  section:
    - HTML
    - RSS
    - ATOM
