baseURL: https://mcamou.github.io/
languageCode: en-us
title: Welcome to the Ï€ dimension
disablePathToLower: true
author:
  name: Mario Camou

theme:
  - hugo-atom-feed
  - mainroad

enableEmoji: true
enableGitInfo: true
disqusShortname: mcamou

permalinks:
  content: /:year/:month/:day/:title/

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - ATOM
  section:
    - HTML
    - RSS
    - ATOM

params: # For the mainroad theme
  subtitle: Software development and other random ramblings
  description: Software, the Universe and Everything
  copyright: Mario Camou
  opengraph: true
  schema: true
  twitter_cards: true
  readmore: false
  authorbox: true
  toc: true
  pager: true
  post_meta:
  #  - author
    - date
    - categories
    - translations
  mainSections:
    - posts
  dateformat: 2006-01-02
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - social
      - search
      - recent
      - categories
      - taglist
  widgets:
    recent_num: 5
    tags_counter: false
    social:
      twitter: thedoc
      linkedin: mcamou
      github: mcamou

